require 'inheritance/bicycle'
require 'inheritance/part'
require 'inheritance/parts'
require 'inheritance/mountain_bike_parts'
require 'inheritance/road_bike_parts'
require 'inheritance/recumbent_bike'
